### ISSUE TITLE
Update dplyr backend

### ISSUE THREAD

**Issue by imanuelcostigan** [imanuelcostigan/RSQLServer#68]
dplyr internals have been [significantly updated](https://github.com/hadley/dplyr/blob/7a4780b083341108a78dcef83e874b5bfa785566/NEWS.md#internals). Need to audit RSQLServer's use of these internals and methods as some non-exported methods were copied across into RSQLServer's code base. 

At least one user has flagged some issues arising from this in #64. Although in my use, I have not yet encountered problems.

**Comment by imanuelcostigan** [comment]
Errors when loading RSQLServer in presence of updated dplyr:

```
Loading RSQLServer
Error: object 'src_translate_env' not found whilst loading namespace 'RSQLServer'
In addition: Warning messages:
1: object ‘src_translate_env’ is not exported by 'namespace:dplyr' 
2: object ‘translate_sql_q’ is not exported by 'namespace:dplyr' 
```

**Comment by imanuelcostigan** [comment]
List of things to go back and fix:

- [ ] number of rows affected by query is not printing when printing tbl results. E.g. `Source:   query [?? x 5]` being printed instead.

**Comment by xinguangliu** [comment]
I also met the same problem after updating the R and packages last night, then I cannot load in the RSQLServer package any more with the same error message, Still not clear how to solve it? Any solution to fix this problem? Thanks.

sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DBI_0.4-1

loaded via a namespace (and not attached):
[1] magrittr_1.5    R6_2.1.2        assertthat_0.1  rsconnect_0.4.3 tools_3.3.0    
[6] dplyr_0.5.0     tibble_1.0      Rcpp_0.12.5

**Comment by imanuelcostigan** [comment]
Nope. Don't update to latest dplyr. Sorry.

**Comment by curtisalexander** [comment]
For those who might have upgraded, downgrade `dplyr` to version `0.4.3`.

```r
pkg_url <- "https://cran.rstudio.com/src/contrib/Archive/dplyr/dplyr_0.4.3.tar.gz"
install.packages(pkg_url, repos = NULL, type = "source")
```

**Comment by imanuelcostigan** [comment]
Thanks @curtisalexander

**Comment by sdhrm22** [comment]
@curtisalexander when i try to install 0.4.3, I get a compile error. I am using R version 3.3.1.

*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="dplyr.dll" OBJECTS="RcppExports.o address.o api.o arrange.o between.o bind.o combine_variables.o distinct.o dplyr.o filter.o group_indices.o init.o join.o select.o strings_addresses.o summarise.o test.o window.o"' had status 127

**ERROR: compilation failed for package 'dplyr'**

* removing 'C:/Users/Admin/Documents/R/win-library/3.3/dplyr'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\Admin\Documents\R\win-library\3.3" "C:/Users/Admin/AppData/Local/Temp/Rtmp0OvKbD/downloaded_packages/dplyr_0.4.3.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/Admin/AppData/Local/Temp/Rtmp0OvKbD/downloaded_packages/dplyr_0.4.3.tar.gz’ had non-zero exit status

**Comment by imanuelcostigan** [comment]
@sdhrm22 please raise your issue to the [dplyr repo](https://github.com/hadley/dplyr). Thanks.

**Comment by mclaeysb** [comment]
Hoping RSQLServer will be able to work with dplyr 0.5.0 soon! 

The workaround works fine for me now, but a fix would greatly simplify the current (and future) implementation of RSQLServer + dplyr here at our NGO!

**Comment by imanuelcostigan** [comment]
@mclaeysb https://github.com/hadley/dplyr/pull/1997#issuecomment-239591576

**Comment by DavudDourvash** [comment]
Hi, is there any new news about RSQLServer  package update??

**Comment by imanuelcostigan** [comment]
@DavudDourvash see #117
